# Generated by Django 5.1.5 on 2025-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registershipforsale',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registershipforsale',
            name='main_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
