# Generated by Django 5.1.5 on 2025-02-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registershipforsale',
            name='hidden_details',
        ),
        migrations.CreateModel(
            name='AdminRegisterShipForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('vessel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=100, null=True)),
                ('year_built', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('LOA', models.CharField(blank=True, max_length=100, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('GRT_NRT', models.CharField(blank=True, max_length=100, null=True)),
                ('Teu', models.CharField(blank=True, max_length=100, null=True)),
                ('main_engine', models.CharField(blank=True, max_length=100, null=True)),
                ('DWT', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ship_image')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='ship_image')),
                ('is_status', models.BooleanField(default=False)),
                ('hidden_details', models.TextField(blank=True, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
        ),
    ]
