# Generated by Django 5.1.5 on 2025-01-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_registershipforsale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registershipforsale',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
