# Generated by Django 5.1.5 on 2025-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_registershipforsale_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterShipForCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection_country', models.CharField(blank=True, max_length=100, null=True)),
                ('year_built', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('desirable_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_as_scrap', models.CharField(blank=True, max_length=100, null=True)),
                ('from_price', models.CharField(blank=True, max_length=100, null=True)),
                ('to_price', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ship_image')),
                ('is_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterShipForEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('is_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cstmuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
