# Generated by Django 5.1.5 on 2025-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_registershipforsale_is_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registershipforsale',
            name='hidden_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
