# Generated by Django 5.1.5 on 2025-02-17 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_registershipforsale_hidden_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershipforsale',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
    ]
