# Generated by Django 5.1.5 on 2025-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_registershipforsale_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershipforsale',
            name='GRT_NRT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
