# Generated by Django 5.1.5 on 2025-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_registershipforsale_grt_nrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershipforsale',
            name='DWT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registershipforsale',
            name='flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
