# Generated by Django 5.1.5 on 2025-02-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_registershipforsale_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershipforsale',
            name='year_built',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
