# Generated by Django 5.1.5 on 2025-01-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_registershipforsale_dwt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registershipforsale',
            name='Class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registershipforsale',
            name='LOA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registershipforsale',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registershipforsale',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registershipforsale',
            name='main_engine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
